### ISSUE TITLE
Кепска працуе

### ISSUE THREAD

**Issue by HaraldZealot** [BSU2013gr0209web/FilipauVV#1]
Ваш тэкст і фон не супадаюць, таму тэкст не відаць. Немагчыма пратэсціць прылажэнне.

**Comment by CloneCody** [comment]
исправил, жду проверки

**Comment by HaraldZealot** [comment]
![snp32](https://cloud.githubusercontent.com/assets/1811725/6769864/e63a56f6-d0bc-11e4-9bcb-45d32bed65d5.png)

Зараз гэта выглядае вось так. Насамрэч вы ўзяліся за вельмі непростую задачу, сагласаваць элементы інтэрфейса якія на розных платформах розныя і фіксіраваны малюнак

**Comment by CloneCody** [comment]
теперь текст виден, кнопка надеюсь залзить не будет
